version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crudapp:latest
    container_name: crudapp_container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/moysklad
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: moysklad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
